<?php
/**
 * Copyright (c) 2016. Radial inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * @see \Magento\Customer\Block\Adminhtml\System\Config\Validatevat
 */
?>
<script>
    require(['prototype'], function(){

//<![CDATA[
        function testApiConnection() {
            var validationMessage = $('validation_result');

            params = {
                apiUrl: $('<?php /* @escapeNotVerified */ echo $block->getApiUrlField(); ?>').value,
                apiKey: $('<?php /* @escapeNotVerified */ echo $block->getApiKeyField(); ?>').value,
                apiStoreId: $('<?php /* @escapeNotVerified */ echo $block->getApiStoreIdField(); ?>').value
            };

            new Ajax.Request('<?php /* @escapeNotVerified */ echo $block->getAjaxUrl() ?>', {
                parameters: params,
                onSuccess: function(response) {
                    var result = '<?php /* @escapeNotVerified */ echo __('Error during API Connection verification.') ?>';
                    try {
                        if (response.responseText.isJSON()) {
                            response = response.responseText.evalJSON();
                            result = response.message;
                        }
                        if (response.valid == 1) {
                            validationMessage.removeClassName('hidden').addClassName('success')
                        } else {
                            validationMessage.removeClassName('hidden').addClassName('error')
                        }
                    } catch (e) {
                        validationMessage.removeClassName('hidden').addClassName('error')
                    }
                    validationMessage.update(result);
                }
            });
        }

        window.testApiConnection = testApiConnection;
//]]>

    });
</script>
<div class="actions actions-test-api-connection">
    <div id="validation_result" class="message-validation hidden"></div>
    <button onclick="javascript:testApiConnection(); return false;" class="action-test-api-connection" type="button" id="<?php echo $block->getHtmlId() ?>">
        <span><?php echo $block->escapeHtml($block->getButtonLabel()) ?></span>
    </button>
</div>
