<?php
/**
 * Copyright (c) 2016. Radial inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * @see \Magento\Customer\Block\Adminhtml\System\Config\Validatevat
 */
?>
<style type="text/css">
    .action-test-api-connection.success{
        background-color: #79a22e;
        color: #fff;
    }
    .action-test-api-connection.failed{
        background-color: #e22626;
        color: #fff;
    }
</style>
<script>
    require(['prototype'], function(){

//<![CDATA[
        function testApiConnection() {
            var validationElem = $('<?php echo $block->getHtmlId() ?>');

            params = {
                apiUrl: $('<?php /* @escapeNotVerified */ echo $block->getApiUrlField(); ?>').value,
                apiKey: $('<?php /* @escapeNotVerified */ echo $block->getApiKeyField(); ?>').value,
                apiStoreId: $('<?php /* @escapeNotVerified */ echo $block->getApiStoreIdField(); ?>').value
            };

            new Ajax.Request('<?php /* @escapeNotVerified */ echo $block->getAjaxUrl() ?>', {
                parameters: params,
                onSuccess: function(response) {
                    var result = '<?php /* @escapeNotVerified */ echo __('Error during API Connection verification.') ?>';
                    try {
                        if (response.responseText.isJSON()) {
                            response = response.responseText.evalJSON();
                            result = response.message;
                        }
                        if (response.valid == 1) {
                            validationElem.removeClassName('failed').addClassName('success')
                        } else {
                            validationElem.removeClassName('success').addClassName('failed')
                        }
                    } catch (e) {
                        validationElem.removeClassName('success').addClassName('failed')
                    }
                    $('validation_result').update(result);
                }
            });
        }

        window.testApiConnection = testApiConnection;
//]]>

    });
</script>
<div class="actions actions-test-api-connection">
    <button onclick="javascript:testApiConnection(); return false;" class="action-test-api-connection" type="button" id="<?php echo $block->getHtmlId() ?>">
        <span id="validation_result"><?php echo $block->escapeHtml($block->getButtonLabel()) ?></span>
    </button>
</div>
